import { ToastProvider } from "@/provider/ToastProvider";

export const metadata = {
  title: "Cart",
  description: "Generated by Yazan",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ToastProvider />
      <body>{children}</body>
    </html>
  );
}
